version: "3"

services:

  backend:
    build:
      context: ./Backend
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - 5000:5000

    volumes:
      - ./Backend/:/backend/

    env_file:
      - ./settings/dev/.env.dev

    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      FLASK_ENV: development
