FROM --platform=linux/x86_64 python:3.8.3-alpine

WORKDIR /backend
COPY requirements.txt /backend/

RUN apk add postgresql-dev libressl-dev libffi-dev gcc g++ musl-dev python3-dev musl-dev zlib-dev jpeg-dev #--(5.2)

RUN pip install --upgrade pip setuptools wheel
RUN pip install -r requirements.txt

COPY . /backend/
