FROM  --platform=linux/x86_64 python:3.7.11-stretch
WORKDIR /backend
COPY requirements.txt /backend/
RUN pip install --upgrade pip setuptools wheel
RUN pip install -r requirements.txt
RUN pip install tensorflow==2.8.0
COPY . /backend/